#!/bin/sh
POSTGRES="psql --username ${POSTGRES_USER}"

echo "Setting up authentication settings"
echo "======"
$POSTGRES <<-SQL
SET password_encryption  = 'scram-sha-256';
SQL

echo "Creating users"
echo "======"

echo "[*] Creating database role: ${TMC_MASTER_USER}... "
$POSTGRES <<-SQL
CREATE USER ${TMC_MASTER_USER} WITH LOGIN PASSWORD '${TMC_MASTER_USER_PASSWORD}';
SQL

echo "[*] Creating database role: ${COM_ADMIN_USER}... "
$POSTGRES <<-SQL
CREATE USER ${COM_ADMIN_USER} WITH LOGIN PASSWORD '${COM_ADMIN_USER_PASSWORD}';
SQL

$POSTGRES <<-SQL
GRANT ${COM_ADMIN_USER} TO ${TMC_MASTER_USER};
SQL

echo "[*] Creating database role: ${COM_SELECT_USER}... "
$POSTGRES <<-SQL
CREATE USER ${COM_SELECT_USER} WITH LOGIN PASSWORD '${COM_SELECT_USER_PASSWORD}';
SQL

echo "[*] Creating database role: ${MEDIA_ADMIN_USER}... "
$POSTGRES <<-SQL
CREATE USER ${MEDIA_ADMIN_USER} WITH LOGIN PASSWORD '${MEDIA_ADMIN_USER_PASSWORD}';
SQL

$POSTGRES <<-SQL
GRANT ${MEDIA_ADMIN_USER} TO ${TMC_MASTER_USER};
SQL

echo "[*] Creating database role: ${MEDIA_SELECT_USER}... "
$POSTGRES <<-SQL
CREATE USER ${MEDIA_SELECT_USER} WITH LOGIN PASSWORD '${MEDIA_SELECT_USER_PASSWORD}';
SQL

echo "[*] Creating database role: ${TMC_SELECT_USER}... "
$POSTGRES <<-SQL
CREATE USER ${TMC_SELECT_USER} WITH LOGIN PASSWORD '${TMC_SELECT_USER_PASSWORD}';
SQL

$POSTGRES <<-SQL
GRANT ${COM_SELECT_USER} TO ${TMC_SELECT_USER};
SQL

$POSTGRES <<-SQL
GRANT ${MEDIA_SELECT_USER} TO ${TMC_SELECT_USER};
SQL

echo "[*] Creating database role: ${EDO_ADMIN_USER}... "
$POSTGRES <<-SQL
CREATE USER ${EDO_ADMIN_USER} WITH LOGIN PASSWORD '${EDO_ADMIN_USER_PASSWORD}';
SQL

$POSTGRES <<-SQL
GRANT ${EDO_ADMIN_USER} TO ${TMC_MASTER_USER};
SQL

echo "[*] Creating database role: ${EDO_SELECT_USER}... "
$POSTGRES <<-SQL
CREATE USER ${EDO_SELECT_USER} WITH LOGIN PASSWORD '${EDO_SELECT_USER_PASSWORD}';
SQL

echo "====="
echo "Users created"
