"""baseline schema

Revision ID: 1787736765
Revises: 
Create Date: 2026-08-26 09:32:45.199077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1787736765'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('blurb', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('variant', sa.Enum('blog', 'workshop', name='variant_enum', schema='com'), server_default='blog', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), sa.Computed('uuid_extract_timestamp(id)', persisted=True), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), sa.Computed('uuid_extract_timestamp(id)', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['com.articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url'),
    schema='com'
    )
    op.create_index(op.f('ix_com_articles_created_at'), 'articles', ['created_at'], unique=False, schema='com')
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('blurb', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag'),
    schema='com'
    )
    op.create_table('everyday_ordinary',
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), sa.Computed('uuid_extract_timestamp(id)', persisted=True), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), sa.Computed('uuid_extract_timestamp(id)', persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='everyday_ordinary'
    )
    op.create_index(op.f('ix_everyday_ordinary_everyday_ordinary_created_at'), 'everyday_ordinary', ['created_at'], unique=False, schema='everyday_ordinary')
    op.create_table('licence',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('text'),
    sa.UniqueConstraint('url'),
    schema='media'
    )
    op.create_table('postcard',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alt_text'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('url'),
    schema='media'
    )
    op.create_table('article_tags_joiner',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['com.articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['com.tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'article_id'),
    schema='com'
    )
    op.create_table('media_item',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('date_published', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('licence_id', sa.Integer(), nullable=False),
    sa.Column('postcard_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'audio', 'gallery', name='media_type_enum', schema='media'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['media.licence.id'], ),
    sa.ForeignKeyConstraint(['postcard_id'], ['media.postcard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('audio_file',
    sa.Column('parent_video', sa.Integer(), nullable=False),
    sa.Column('bit_rate', sa.Integer(), nullable=False),
    sa.Column('bit_depth', sa.String(), nullable=False),
    sa.Column('sample_rate', sa.String(), nullable=False),
    sa.Column('vbr_encoded', sa.Boolean(), nullable=False),
    sa.Column('audio_codec', sa.Enum('vorbis', 'mp3', 'wav', name='audio_audio_codec', schema='media'), nullable=False),
    sa.Column('mime_type', sa.Enum('webm', 'mp3', 'ogg', 'mpeg', 'wav', name='audio_mime_type', schema='media'), nullable=False),
    sa.Column('extension', sa.Enum('wav', 'ogg', 'mp3', name='audio_file_extension', schema='media'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_video'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('audio_track',
    sa.Column('parent_audio', sa.Integer(), nullable=False),
    sa.Column('src_lang', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('track_type', sa.Enum('subtitles', 'captions', 'descriptions', 'chapters', 'metadata', name='audio_track_type', schema='media'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_audio'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blurb', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('video_file',
    sa.Column('parent_video', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('is_fullscreen', sa.Boolean(), nullable=False),
    sa.Column('video_codec', sa.Enum('vp8', 'h264', 'theora', name='video_video_codec', schema='media'), nullable=False),
    sa.Column('audio_codec', sa.Enum('nill', 'vorbis', 'mp3', 'wav', name='video_audio_codec', schema='media'), nullable=False),
    sa.Column('mime_type', sa.Enum('webm', 'mp4', 'ogg', name='video_mime_type', schema='media'), nullable=False),
    sa.Column('extension', sa.Enum('webm', 'ogv', 'mp4', name='video_file_extension', schema='media'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_video'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('video_track',
    sa.Column('parent_video', sa.Integer(), nullable=False),
    sa.Column('src_lang', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('track_type', sa.Enum('subtitles', 'captions', 'descriptions', 'chapters', 'metadata', name='video_track_type', schema='media'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_video'], ['media.media_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    op.create_table('image',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['media.gallery.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='media'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image', schema='media')
    op.drop_table('video_track', schema='media')
    op.drop_table('video_file', schema='media')
    op.drop_table('video', schema='media')
    op.drop_table('gallery', schema='media')
    op.drop_table('audio_track', schema='media')
    op.drop_table('audio_file', schema='media')
    op.drop_table('audio', schema='media')
    op.drop_table('media_item', schema='media')
    op.drop_table('article_tags_joiner', schema='com')
    op.drop_table('postcard', schema='media')
    op.drop_table('licence', schema='media')
    op.drop_index(op.f('ix_everyday_ordinary_everyday_ordinary_created_at'), table_name='everyday_ordinary', schema='everyday_ordinary')
    op.drop_table('everyday_ordinary', schema='everyday_ordinary')
    op.drop_table('tags', schema='com')
    op.drop_index(op.f('ix_com_articles_created_at'), table_name='articles', schema='com')
    op.drop_table('articles', schema='com')
    # ### end Alembic commands ###
