"""Corrected the self referential parent/child article setup

Revision ID: 3577e4c322c6
Revises: e2db1cd43fd9
Create Date: 2018-10-24 20:57:32.290044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3577e4c322c6'
down_revision = 'e2db1cd43fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('parent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'articles', ['parent'], ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'parent')
    # ### end Alembic commands ###
