"""Fixed the id and reference for article self referencing with foreign key

Revision ID: 551f78f9d8a5
Revises: 8e01032c9c5e
Create Date: 2018-11-17 19:13:52.491349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551f78f9d8a5'
down_revision = '8e01032c9c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('articles_parent_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'articles', ['parent_id'], ['id'])
    op.drop_column('articles', 'parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_parent_fkey', 'articles', 'articles', ['parent'], ['id'])
    op.drop_column('articles', 'parent_id')
    # ### end Alembic commands ###
