"""Tags have descriptions now.

Revision ID: 6456a799202c
Revises: 551f78f9d8a5
Create Date: 2019-08-18 21:03:04.444843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6456a799202c'
down_revision = '551f78f9d8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('blurb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'blurb')
    # ### end Alembic commands ###
