"""EDO API getting built on UUID4 ABC

Revision ID: 815278b451a7
Revises: 6456a799202c
Create Date: 2022-11-07 20:25:02.054384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '815278b451a7'
down_revision = '6456a799202c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('everyday_ordinary.everyday_ordinary',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('contents', sa.String(), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('deleted_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('everyday_ordinary.everyday_ordinary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_everyday_ordinary_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_everyday_ordinary_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_everyday_ordinary_updated_at'), ['updated_at'], unique=False)

    op.drop_table('migrate_version')

    with op.batch_alter_table('media.media_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'media.postcard', ['media.postcard'], ['id'])

    with op.batch_alter_table('media.tags_joiner', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'media.tags', ['media.tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media.tags_joiner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('media.media_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name='migrate_version_pkey')
    )
    with op.batch_alter_table('everyday_ordinary.everyday_ordinary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_everyday_ordinary_updated_at'))
        batch_op.drop_index(batch_op.f('ix_everyday_ordinary_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_everyday_ordinary_created_at'))

    op.drop_table('everyday_ordinary.everyday_ordinary')
    # ### end Alembic commands ###
