"""Blurb for the article

Revision ID: 8e01032c9c5e
Revises: 0893e5f2954f
Create Date: 2018-11-09 20:44:50.013098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e01032c9c5e'
down_revision = '0893e5f2954f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('blurb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'blurb')
    # ### end Alembic commands ###
