[uwsgi]
uid = www-data
gid = www-data

chdir = /srv/http/www.themetacity.test/
plugin = python3
pythonpath = /srv/virtualenv/theMetaCity/bin/python3
virtualenv = /srv/virtualenv/theMetaCity
wsgi-file = theMetaCity.wsgi
#module = theMetaCity:app

need-app = true

#socket = /tmp/theMetaCityTestSocket
chmod-socket = 664

die-on-term = true

master = true
processes = 5

logto = /var/log/uwsgi/app/www.themetacity.test.log
log-5xx = true
disable-logging = false

env = FLASK_ENV=development